/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** O processo está de pé (liveness) */
        get: operations["vivacidade"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A API consegue atender, com banco acessível (readiness) */
        get: operations["prontidao"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Erro no formato RFC 9457 (application/problem+json) */
        ProblemDetails: {
            /** @description Código estável para o front (ex.: NAO_ENCONTRADO) */
            code: string;
            /** @description Ausente em erros 5xx */
            detail?: string;
            /** @description Erros por campo (DADOS_INVALIDOS) */
            errors?: {
                /** @description Caminho do campo, com "." nos aninhados (ex.: item.quantidade) */
                campo: string;
                mensagem: string;
            }[];
            /** @description Caminho da requisição */
            instance: string;
            /** @description Mesmo valor do header X-Request-Id */
            requestId?: string;
            status: number;
            title: string;
            /** Format: uri */
            type: string;
        };
        RespostaProntidaoDto: {
            details: {
                database: {
                    /** @enum {string} */
                    status: "up" | "down";
                };
            };
            /** @enum {string} */
            status: "ok" | "error";
        };
        RespostaVivacidadeDto: {
            /** @enum {string} */
            status: "ok";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    vivacidade: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Processo de pé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaVivacidadeDto"];
                };
            };
        };
    };
    prontidao: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pronta para atender */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaProntidaoDto"];
                };
            };
            /** @description Algum componente está fora do ar */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaProntidaoDto"];
                };
            };
        };
    };
}
