/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Áreas ativas, em ordem de nome (pública) */
        get: operations["listarAreas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auditoria/integridade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recalcula a corrente de hash do histórico de todas as solicitações e aponta as divergências */
        get: operations["integridadeHistorico"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autentica e abre uma sessão */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Encerra a sessão (revoga a família inteira) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuário autenticado, com a área */
        get: operations["usuarioAtual"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Troca o refresh token por um novo par */
        post: operations["renovarSessao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/gestao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Painel de gestão do administrador: entrada e saída, por área, por analista e integrações com falha */
        get: operations["gestaoDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/resumo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Totais por status e prioridade no escopo do usuário, no período escolhido */
        get: operations["resumoDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/solicitacoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista com busca, filtros, ordenação e paginação (escopo do usuário) */
        get: operations["listarSolicitacoes"];
        put?: never;
        /** Abre uma solicitação (nasce ABERTA) */
        post: operations["criarSolicitacao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/solicitacoes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe, com as ações permitidas ao usuário atual */
        get: operations["detalharSolicitacao"];
        put?: never;
        post?: never;
        /** Exclusão lógica (dono com ABERTA ou administrador sem decisão) */
        delete: operations["excluirSolicitacao"];
        options?: never;
        head?: never;
        /** Edita título, descrição e prioridade (dono com ABERTA ou administrador sem decisão) */
        patch: operations["editarSolicitacao"];
        trace?: never;
    };
    "/api/v1/solicitacoes/{id}/analise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia a análise (ABERTA → EM_ANALISE); quem inicia vira o responsável */
        post: operations["iniciarAnalise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/solicitacoes/{id}/decisao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aprova ou rejeita com comentário (analista responsável ou administrador) */
        post: operations["decidirSolicitacao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/solicitacoes/{id}/historico": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Linha do tempo, do evento mais antigo para o mais recente */
        get: operations["historicoSolicitacao"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/solicitacoes/{id}/integracao/reprocessamento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Devolve à fila o evento de integração em FALHOU mais antigo (PENDENTE, tentativas zeradas); administrador */
        post: operations["reprocessarIntegracao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/solicitacoes/{id}/reabertura": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reabre uma decidida (→ ABERTA) com justificativa (administrador) */
        post: operations["reabrirSolicitacao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** O processo está de pé (liveness) */
        get: operations["vivacidade"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A API consegue atender, com banco acessível (readiness) */
        get: operations["prontidao"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AreaDto: {
            /**
             * Format: uuid
             * @example 1a3c5e7b-9d2f-4b46-8c0e-7f9a1b3d5e28
             */
            id: string;
            /** @example Financeiro */
            nome: string;
        };
        /** @description Solicitante, área, data e status vêm do servidor e não são aceitos */
        CriarSolicitacaoDto: {
            /**
             * @description 10 a 5000 caracteres, com pelo menos 10 que não sejam espaço; gravada sem trim
             * @example Preciso de acesso de leitura ao módulo de cobrança para conciliar os boletos do mês.
             */
            descricao: string;
            /**
             * @example ALTA
             * @enum {string}
             */
            prioridade: "BAIXA" | "MEDIA" | "ALTA";
            /**
             * @description 5 a 120 caracteres, sem contar os espaços nas pontas
             * @example Acesso ao sistema de cobrança
             */
            titulo: string;
        };
        DecisaoDto: {
            /** @example Acesso liberado conforme a política de perfis de leitura. */
            comentario: string;
            /**
             * @example APROVADA
             * @enum {string}
             */
            resultado: "APROVADA" | "REJEITADA";
        };
        DivergenciaHistorico: {
            /**
             * Format: date-time
             * @example 2026-10-03T10:12:00.000Z
             */
            criadoEm: string;
            /**
             * Format: uuid
             * @example c7e1a9d3-5b2f-4c86-9e0a-4d6f8b2c1e57
             */
            eventoId: string;
            motivo: components["schemas"]["MotivoDivergencia"];
            solicitacao: {
                /** @example SOL-000042 */
                codigo: string;
                /**
                 * Format: uuid
                 * @example 0b6c8f9e-3d2a-4f7b-9c1e-5a8d2f4b6c10
                 */
                id: string;
            };
            /**
             * @example APROVADA
             * @enum {string}
             */
            tipo: "CRIADA" | "EDITADA" | "ANALISE_INICIADA" | "APROVADA" | "REJEITADA" | "REABERTA" | "EXCLUIDA";
        };
        /** @description Só título, descrição e prioridade; o status muda pelos comandos */
        EditarSolicitacaoDto: {
            /**
             * @description 10 a 5000 caracteres, com pelo menos 10 que não sejam espaço; gravada sem trim
             * @example Preciso de acesso de leitura ao módulo de cobrança para conciliar os boletos do mês.
             */
            descricao?: string;
            /**
             * @example MEDIA
             * @enum {string}
             */
            prioridade?: "BAIXA" | "MEDIA" | "ALTA";
            /**
             * @description 5 a 120 caracteres, sem contar os espaços nas pontas
             * @example Acesso de leitura ao sistema de cobrança
             */
            titulo?: string;
            /**
             * @description Versão lida; se outra pessoa alterou antes, a resposta é 409 CONFLITO_DE_VERSAO
             * @example 1
             */
            versao: number;
        };
        EventoHistoricoDto: {
            /**
             * @example {
             *       "id": "8d2f4a6c-1e3b-4c75-9a0d-2b4e6f8a1c39",
             *       "nome": "Carla Mendes"
             *     }
             */
            autor: {
                /** Format: uuid */
                id: string;
                nome: string;
            };
            /**
             * @description Comentário da decisão ou justificativa da reabertura
             * @example Acesso liberado conforme a política de perfis de leitura.
             */
            comentario: string | null;
            /**
             * Format: date-time
             * @example 2026-10-03T10:12:00.000Z
             */
            criadoEm: string;
            /**
             * @description EDITADA: { campo: { antes, depois } }; REABERTA: { decisaoAnterior: { resultado, comentario, decididoEm, decididoPor, analista } }
             * @example null
             */
            dados: {
                [key: string]: unknown;
            } | null;
            /**
             * Format: uuid
             * @example c7e1a9d3-5b2f-4c86-9e0a-4d6f8b2c1e57
             */
            id: string;
            /**
             * @example EM_ANALISE
             * @enum {string|null}
             */
            statusAnterior: "ABERTA" | "EM_ANALISE" | "APROVADA" | "REJEITADA" | null;
            /**
             * @description null em eventos que não mudam status (EDITADA)
             * @example APROVADA
             * @enum {string|null}
             */
            statusNovo: "ABERTA" | "EM_ANALISE" | "APROVADA" | "REJEITADA" | null;
            /**
             * @example APROVADA
             * @enum {string}
             */
            tipo: "CRIADA" | "EDITADA" | "ANALISE_INICIADA" | "APROVADA" | "REJEITADA" | "REABERTA" | "EXCLUIDA";
        };
        GestaoDto: {
            /** @description Entrada e saída da fila, pelos eventos do histórico (excluídas ficam fora) */
            entradaSaida: {
                /** @description null em hoje e tudo */
                anterior: {
                    entraram: number;
                    sairam: number;
                    /** @description null sem decisões na janela anterior */
                    tempoMedioDecisaoDias: number | null;
                } | null;
                /** @example 7 */
                aprovadas: number;
                /**
                 * @description Eventos CRIADA e REABERTA no período
                 * @example 12
                 */
                entraram: number;
                /** @description ABERTA mais antiga (estado atual, ignora o período) */
                maisAntigaNaFila: {
                    area: {
                        /** Format: uuid */
                        id: string;
                        nome: string;
                    };
                    /** @example SOL-000009 */
                    codigo: string;
                    /**
                     * Format: date-time
                     * @description dataSolicitacao da solicitação
                     */
                    desde: string;
                    /** Format: uuid */
                    id: string;
                } | null;
                /** @description ABERTA e EM_ANALISE agora (ignora o período) */
                pendentesPorPrioridade: {
                    ALTA: number;
                    BAIXA: number;
                    MEDIA: number;
                };
                /** @description Entradas do período pela prioridade */
                prioridadeEntraram: {
                    ALTA: number;
                    BAIXA: number;
                    MEDIA: number;
                };
                /** @example 3 */
                rejeitadas: number;
                /**
                 * @description Eventos APROVADA e REJEITADA no período
                 * @example 10
                 */
                sairam: number;
                /**
                 * @description entraram − saíram
                 * @example 2
                 */
                saldo: number;
                /** @description Baldes do período, com zero onde não houve evento */
                serie: {
                    entraram: number;
                    /**
                     * Format: date-time
                     * @description Início do balde no fuso America/Sao_Paulo
                     */
                    inicio: string;
                    sairam: number;
                }[];
                /**
                 * @description Média, em dias, de (decisão − dataSolicitacao) das decisões do período
                 * @example 10
                 */
                tempoMedioDecisaoDias: number | null;
            };
            /**
             * Format: date-time
             * @example 2026-10-04T10:15:00.000Z
             */
            geradoEm: string;
            /** @description Evento em foco FALHOU, da tentativa mais recente para a mais antiga (estado atual) */
            integracoesComFalha: {
                /** @example 5 */
                maxTentativas: number;
                solicitacao: {
                    area: {
                        /** Format: uuid */
                        id: string;
                        nome: string;
                    };
                    /** @example SOL-000024 */
                    codigo: string;
                    /** Format: uuid */
                    id: string;
                    solicitante: {
                        /** Format: uuid */
                        id: string;
                        nome: string;
                    };
                    titulo: string;
                };
                /** @example 5 */
                tentativas: number;
                /**
                 * @description Tipo do evento em foco
                 * @example SolicitacaoAprovada
                 */
                tipo: string;
                /**
                 * Format: date-time
                 * @example 2026-10-04T09:40:00.000Z
                 */
                ultimaTentativaEm: string | null;
                /**
                 * @description Último erro do sistema externo, cortado em 300 caracteres
                 * @example Sistema externo respondeu 503
                 */
                ultimoErro: string | null;
            }[];
            /** @description Período aplicado à entrada e saída, por área e por analista */
            periodo: {
                /**
                 * Format: date-time
                 * @description Instante da consulta
                 * @example 2026-10-04T10:15:00.000Z
                 */
                fim: string;
                /**
                 * @description Balde da série: dia (7d), semana (30d e tudo até 16 semanas) ou mes; null em hoje
                 * @example dia
                 */
                granularidade: components["schemas"]["Granularidade"] | null;
                /**
                 * Format: date-time
                 * @description Início inclusivo; null em tudo
                 * @example 2026-09-27T10:15:00.000Z
                 */
                inicio: string | null;
                /** @enum {string} */
                valor: "hoje" | "7d" | "30d" | "tudo";
            };
            /** @description Analistas e admins ativos com análise agora ou decisão no período, por emAnaliseAgora desc e nome */
            porAnalista: {
                analista: {
                    /** Format: uuid */
                    id: string;
                    nome: string;
                };
                aprovadas: number;
                /** @description Eventos APROVADA e REJEITADA da pessoa no período */
                decididas: number;
                /** @description EM_ANALISE com a pessoa agora (ignora o período) */
                emAnaliseAgora: number;
                /**
                 * @description aprovadas / decididas; null sem decisões
                 * @example 0.7
                 */
                taxaAprovacao: number | null;
            }[];
            /** @description Todas as áreas ativas, inclusive as zeradas */
            porArea: {
                area: {
                    /** Format: uuid */
                    id: string;
                    nome: string;
                };
                porStatus: {
                    ABERTA: number;
                    APROVADA: number;
                    EM_ANALISE: number;
                    REJEITADA: number;
                };
                /** @description Solicitações da área com dataSolicitacao no período */
                total: number;
            }[];
        };
        /**
         * @example dia
         * @enum {string}
         */
        Granularidade: "dia" | "semana" | "mes";
        IntegridadeDto: {
            /** @description Até 20, da mais antiga para a mais recente */
            divergencias: components["schemas"]["DivergenciaHistorico"][];
            /** @example 412 */
            eventosVerificados: number;
            /** @description true quando nenhuma divergência foi encontrada */
            integro: boolean;
            /**
             * @description Inclui solicitações excluídas logicamente
             * @example 40
             */
            solicitacoesVerificadas: number;
            /** @example 1 */
            totalDivergencias: number;
            /**
             * Format: date-time
             * @example 2026-10-04T10:15:00.000Z
             */
            verificadoEm: string;
        };
        LoginDto: {
            /**
             * @description Aceita maiúsculas e espaços nas pontas (normalizado antes da busca)
             * @example ana.souza@demo.test
             */
            email: string;
            /** @example Demo@2026 */
            senha: string;
        };
        /**
         * @description CONTEUDO_ALTERADO: o conteúdo do evento não confere com o hash gravado; CORRENTE_QUEBRADA: o evento não aponta para o anterior (evento apagado ou inserido no meio)
         * @example CONTEUDO_ALTERADO
         * @enum {string}
         */
        MotivoDivergencia: "CONTEUDO_ALTERADO" | "CORRENTE_QUEBRADA";
        PaginaSolicitacoesDto: {
            data: {
                /**
                 * Format: date-time
                 * @description Início da análise atual: o último ANALISE_INICIADA depois da última reabertura. Só em EM_ANALISE; null nos demais status
                 * @example null
                 */
                analiseIniciadaEm: string | null;
                /**
                 * @description Analista responsável; null até a análise começar
                 * @example {
                 *       "id": "8d2f4a6c-1e3b-4c75-9a0d-2b4e6f8a1c39",
                 *       "nome": "Carla Mendes"
                 *     }
                 */
                analista: {
                    /** Format: uuid */
                    id: string;
                    nome: string;
                } | null;
                /**
                 * @description Área do solicitante na criação
                 * @example {
                 *       "id": "1a3c5e7b-9d2f-4b46-8c0e-7f9a1b3d5e28",
                 *       "nome": "Financeiro"
                 *     }
                 */
                area: {
                    /** Format: uuid */
                    id: string;
                    nome: string;
                };
                /**
                 * Format: date-time
                 * @example 2026-10-03T10:12:00.000Z
                 */
                atualizadoEm: string;
                /**
                 * @description Código de exibição, ex.: SOL-000042
                 * @example SOL-000042
                 */
                codigo: string;
                /**
                 * Format: date-time
                 * @example 2026-10-02T13:45:00.000Z
                 */
                dataSolicitacao: string;
                /**
                 * @description Decisão vigente; null enquanto não houver decisão ou depois de uma reabertura
                 * @example {
                 *       "comentario": "Acesso liberado conforme a política de perfis de leitura.",
                 *       "decididoEm": "2026-10-03T10:12:00.000Z",
                 *       "decididoPor": {
                 *         "id": "8d2f4a6c-1e3b-4c75-9a0d-2b4e6f8a1c39",
                 *         "nome": "Carla Mendes"
                 *       },
                 *       "resultado": "APROVADA"
                 *     }
                 */
                decisao: {
                    comentario: string;
                    /** Format: date-time */
                    decididoEm: string;
                    decididoPor: {
                        /** Format: uuid */
                        id: string;
                        nome: string;
                    };
                    /** @enum {string} */
                    resultado: "APROVADA" | "REJEITADA";
                } | null;
                /**
                 * Format: uuid
                 * @example 0b6c8f9e-3d2a-4f7b-9c1e-5a8d2f4b6c10
                 */
                id: string;
                /**
                 * @example ALTA
                 * @enum {string}
                 */
                prioridade: "BAIXA" | "MEDIA" | "ALTA";
                /**
                 * @example {
                 *       "id": "3e7b1c9a-2d4f-4a68-8b0e-6c1d3f5a7b92",
                 *       "nome": "Ana Souza"
                 *     }
                 */
                solicitante: {
                    /** Format: uuid */
                    id: string;
                    nome: string;
                };
                /**
                 * @example APROVADA
                 * @enum {string}
                 */
                status: "ABERTA" | "EM_ANALISE" | "APROVADA" | "REJEITADA";
                /** @example Acesso ao sistema de cobrança */
                titulo: string;
            }[];
            /**
             * @example {
             *       "page": 1,
             *       "pageSize": 20,
             *       "total": 42,
             *       "totalPages": 3
             *     }
             */
            meta: {
                page: number;
                pageSize: number;
                total: number;
                /** @description 0 quando não há resultados */
                totalPages: number;
            };
        };
        /** @description Erro no formato RFC 9457 (application/problem+json) */
        ProblemDetails: {
            /**
             * @description Código estável para o front (ex.: NAO_ENCONTRADO)
             * @example TRANSICAO_INVALIDA
             */
            code: string;
            /**
             * @description Ausente em erros 5xx
             * @example Uma solicitação com status Aberta não pode ser aprovada. Inicie a análise primeiro.
             */
            detail?: string;
            /**
             * @description Erros por campo (DADOS_INVALIDOS)
             * @example [
             *       {
             *         "campo": "titulo",
             *         "mensagem": "O título deve ter pelo menos 5 caracteres."
             *       }
             *     ]
             */
            errors?: {
                /** @description Caminho do campo, com "." nos aninhados (ex.: item.quantidade) */
                campo: string;
                mensagem: string;
            }[];
            /**
             * @description Caminho da requisição
             * @example /api/v1/solicitacoes/0b6c8f9e-3d2a-4f7b-9c1e-5a8d2f4b6c10/decisao
             */
            instance: string;
            /**
             * @description Mesmo valor do header X-Request-Id
             * @example f3c1a2b4-6d8e-4f0a-9b1c-3e5d7f9a2b46
             */
            requestId?: string;
            /** @example 409 */
            status: number;
            /** @example Transição de status inválida */
            title: string;
            /**
             * Format: uri
             * @example https://solicitacoes.local/erros/transicao-invalida
             */
            type: string;
        };
        ReaberturaDto: {
            /** @example A aprovação considerou o perfil errado; precisa de nova análise. */
            justificativa: string;
        };
        RefreshDto: {
            /** @example q9fV3kz8Lw1mT0rB6yHc2pNs5uXa7dGe4jQiOtRlUvW */
            refreshToken: string;
        };
        RespostaProntidaoDto: {
            /**
             * @example {
             *       "database": {
             *         "status": "up"
             *       }
             *     }
             */
            details: {
                database: {
                    /** @enum {string} */
                    status: "up" | "down";
                };
            };
            /**
             * @example ok
             * @enum {string}
             */
            status: "ok" | "error";
        };
        RespostaSessaoDto: {
            /**
             * Format: date-time
             * @description Fim da validade do access token (UTC)
             * @example 2026-10-03T13:15:00.000Z
             */
            accessExpiraEm: string;
            /**
             * @description JWT (HS256) para o header Authorization: Bearer
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIuLi4ifQ.assinatura
             */
            accessToken: string;
            /**
             * Format: date-time
             * @description Fim da validade do refresh token (UTC)
             * @example 2026-10-10T13:00:00.000Z
             */
            refreshExpiraEm: string;
            /**
             * @description Token opaco, de uso único, para POST /auth/refresh
             * @example q9fV3kz8Lw1mT0rB6yHc2pNs5uXa7dGe4jQiOtRlUvW
             */
            refreshToken: string;
            /**
             * @example {
             *       "area": {
             *         "id": "1a3c5e7b-9d2f-4b46-8c0e-7f9a1b3d5e28",
             *         "nome": "Financeiro"
             *       },
             *       "cargo": "SOLICITANTE",
             *       "email": "ana.souza@demo.test",
             *       "id": "3e7b1c9a-2d4f-4a68-8b0e-6c1d3f5a7b92",
             *       "nome": "Ana Souza"
             *     }
             */
            usuario: {
                /**
                 * @example {
                 *       "id": "1a3c5e7b-9d2f-4b46-8c0e-7f9a1b3d5e28",
                 *       "nome": "Financeiro"
                 *     }
                 */
                area: {
                    /** Format: uuid */
                    id: string;
                    nome: string;
                };
                /**
                 * @example SOLICITANTE
                 * @enum {string}
                 */
                cargo: "SOLICITANTE" | "ANALISTA" | "ADMIN";
                /** @example ana.souza@demo.test */
                email: string;
                /**
                 * Format: uuid
                 * @example 3e7b1c9a-2d4f-4a68-8b0e-6c1d3f5a7b92
                 */
                id: string;
                /** @example Ana Souza */
                nome: string;
            };
        };
        RespostaVivacidadeDto: {
            /**
             * @example ok
             * @enum {string}
             */
            status: "ok";
        };
        ResumoDto: {
            /**
             * Format: date-time
             * @description dataSolicitacao da ABERTA mais antiga no escopo, ou null (ignora o período)
             * @example 2026-09-20T09:00:00.000Z
             */
            aberturaMaisAntiga: string | null;
            /**
             * @description GERAL para analista e administrador; PROPRIAS para o solicitante
             * @example GERAL
             * @enum {string}
             */
            escopo: "GERAL" | "PROPRIAS";
            /**
             * @description ABERTA de prioridade ALTA no escopo (ignora o período)
             * @example 3
             */
            filaAlta: number;
            /**
             * Format: date-time
             * @example 2026-10-03T10:15:00.000Z
             */
            geradoEm: string;
            /**
             * @description Período aplicado a total, porStatus e porPrioridade
             * @example {
             *       "fim": "2026-10-04T10:15:00.000Z",
             *       "inicio": "2026-09-27T10:15:00.000Z",
             *       "valor": "7d"
             *     }
             */
            periodo: {
                /**
                 * Format: date-time
                 * @description Instante da consulta
                 * @example 2026-10-04T10:15:00.000Z
                 */
                fim: string;
                /**
                 * Format: date-time
                 * @description Início inclusivo; null em tudo
                 * @example 2026-09-27T10:15:00.000Z
                 */
                inicio: string | null;
                /** @enum {string} */
                valor: "hoje" | "7d" | "30d" | "tudo";
            };
            /**
             * @example {
             *       "ALTA": 10,
             *       "BAIXA": 12,
             *       "MEDIA": 20
             *     }
             */
            porPrioridade: {
                ALTA: number;
                BAIXA: number;
                MEDIA: number;
            };
            /**
             * @example {
             *       "ABERTA": 10,
             *       "APROVADA": 18,
             *       "EM_ANALISE": 7,
             *       "REJEITADA": 7
             *     }
             */
            porStatus: {
                ABERTA: number;
                APROVADA: number;
                EM_ANALISE: number;
                REJEITADA: number;
            };
            /**
             * @description Solicitações no escopo com dataSolicitacao no período
             * @example 42
             */
            total: number;
        };
        SolicitacaoDto: {
            /**
             * @description O que o usuário atual pode fazer agora; a UI só mostra esses botões
             * @example [
             *       "REABRIR"
             *     ]
             */
            acoesPermitidas: ("EDITAR" | "EXCLUIR" | "INICIAR_ANALISE" | "DECIDIR" | "REABRIR" | "REPROCESSAR_INTEGRACAO")[];
            /**
             * @description Analista responsável; null até a análise começar
             * @example {
             *       "id": "8d2f4a6c-1e3b-4c75-9a0d-2b4e6f8a1c39",
             *       "nome": "Carla Mendes"
             *     }
             */
            analista: {
                /** Format: uuid */
                id: string;
                nome: string;
            } | null;
            /**
             * @description Área do solicitante na criação
             * @example {
             *       "id": "1a3c5e7b-9d2f-4b46-8c0e-7f9a1b3d5e28",
             *       "nome": "Financeiro"
             *     }
             */
            area: {
                /** Format: uuid */
                id: string;
                nome: string;
            };
            /**
             * Format: date-time
             * @example 2026-10-03T10:12:00.000Z
             */
            atualizadoEm: string;
            /**
             * @description Código de exibição, ex.: SOL-000042
             * @example SOL-000042
             */
            codigo: string;
            /**
             * Format: date-time
             * @example 2026-10-02T13:45:00.000Z
             */
            dataSolicitacao: string;
            /**
             * @description Decisão vigente; null enquanto não houver decisão ou depois de uma reabertura
             * @example {
             *       "comentario": "Acesso liberado conforme a política de perfis de leitura.",
             *       "decididoEm": "2026-10-03T10:12:00.000Z",
             *       "decididoPor": {
             *         "id": "8d2f4a6c-1e3b-4c75-9a0d-2b4e6f8a1c39",
             *         "nome": "Carla Mendes"
             *       },
             *       "resultado": "APROVADA"
             *     }
             */
            decisao: {
                comentario: string;
                /** Format: date-time */
                decididoEm: string;
                decididoPor: {
                    /** Format: uuid */
                    id: string;
                    nome: string;
                };
                /** @enum {string} */
                resultado: "APROVADA" | "REJEITADA";
            } | null;
            /** @example Preciso de acesso de leitura ao módulo de cobrança para conciliar os boletos do mês. */
            descricao: string;
            /**
             * Format: uuid
             * @example 0b6c8f9e-3d2a-4f7b-9c1e-5a8d2f4b6c10
             */
            id: string;
            /**
             * @description Integração com o sistema externo (ADR-010); null se a solicitação não tem evento
             * @example {
             *       "aguardando": 0,
             *       "enviadaEm": "2026-10-03T10:12:07.000Z",
             *       "eventos": [
             *         {
             *           "criadoEm": "2026-10-03T10:12:00.000Z",
             *           "enviadaEm": "2026-10-03T10:12:07.000Z",
             *           "id": "5f1d7c2a-8b3e-4a69-b0d4-2e9c6a1f7d38",
             *           "status": "ENVIADO",
             *           "tentativas": 2,
             *           "tipo": "SolicitacaoAprovada"
             *         }
             *       ],
             *       "maxTentativas": 8,
             *       "proximaTentativaEm": "2026-10-03T10:12:00.000Z",
             *       "status": "ENVIADO",
             *       "tentativas": 2,
             *       "tipo": "SolicitacaoAprovada"
             *     }
             */
            integracao: {
                /**
                 * @description Eventos não enviados atrás do evento em foco
                 * @example 0
                 */
                aguardando: number;
                /**
                 * Format: date-time
                 * @description Quando o evento em foco foi entregue; null se ainda não foi
                 * @example 2026-10-03T10:12:07.000Z
                 */
                enviadaEm: string | null;
                /**
                 * @description Todos os eventos da solicitação, em ordem cronológica
                 * @example [
                 *       {
                 *         "criadoEm": "2026-10-03T10:12:00.000Z",
                 *         "enviadaEm": "2026-10-03T10:12:07.000Z",
                 *         "id": "5f1d7c2a-8b3e-4a69-b0d4-2e9c6a1f7d38",
                 *         "status": "ENVIADO",
                 *         "tentativas": 2,
                 *         "tipo": "SolicitacaoAprovada"
                 *       }
                 *     ]
                 */
                eventos: {
                    /** Format: date-time */
                    criadoEm: string;
                    /**
                     * Format: date-time
                     * @description null enquanto não for entregue
                     */
                    enviadaEm: string | null;
                    /**
                     * Format: uuid
                     * @description Id do evento (também a chave de idempotência do envio)
                     */
                    id: string;
                    /** @enum {string} */
                    status: "PENDENTE" | "ENVIADO" | "FALHOU";
                    tentativas: number;
                    /** @enum {string} */
                    tipo: "SolicitacaoAprovada" | "SolicitacaoReaberta";
                }[];
                /**
                 * @description Limite de tentativas automáticas (depois, FALHOU)
                 * @example 8
                 */
                maxTentativas: number;
                /**
                 * Format: date-time
                 * @description Quando o evento em foco será tentado (relevante só em PENDENTE)
                 * @example 2026-10-03T10:12:00.000Z
                 */
                proximaTentativaEm: string;
                /**
                 * @description Status do evento em foco: o mais antigo ainda não enviado (segura a fila da solicitação) ou, se todos foram enviados, o mais recente
                 * @example ENVIADO
                 * @enum {string}
                 */
                status: "PENDENTE" | "ENVIADO" | "FALHOU";
                /**
                 * @description Tentativas já feitas para o evento em foco
                 * @example 2
                 */
                tentativas: number;
                /**
                 * @description Tipo do evento em foco
                 * @example SolicitacaoAprovada
                 * @enum {string}
                 */
                tipo: "SolicitacaoAprovada" | "SolicitacaoReaberta";
            } | null;
            /**
             * @example ALTA
             * @enum {string}
             */
            prioridade: "BAIXA" | "MEDIA" | "ALTA";
            /**
             * @example {
             *       "id": "3e7b1c9a-2d4f-4a68-8b0e-6c1d3f5a7b92",
             *       "nome": "Ana Souza"
             *     }
             */
            solicitante: {
                /** Format: uuid */
                id: string;
                nome: string;
            };
            /**
             * @example APROVADA
             * @enum {string}
             */
            status: "ABERTA" | "EM_ANALISE" | "APROVADA" | "REJEITADA";
            /** @example Acesso ao sistema de cobrança */
            titulo: string;
            /**
             * @description Envie no PATCH para o controle de concorrência
             * @example 3
             */
            versao: number;
        };
        UsuarioAtualDto: {
            /**
             * @example {
             *       "id": "1a3c5e7b-9d2f-4b46-8c0e-7f9a1b3d5e28",
             *       "nome": "Financeiro"
             *     }
             */
            area: {
                /** Format: uuid */
                id: string;
                nome: string;
            };
            /**
             * @example SOLICITANTE
             * @enum {string}
             */
            cargo: "SOLICITANTE" | "ANALISTA" | "ADMIN";
            /** @example ana.souza@demo.test */
            email: string;
            /**
             * Format: uuid
             * @example 3e7b1c9a-2d4f-4a68-8b0e-6c1d3f5a7b92
             */
            id: string;
            /** @example Ana Souza */
            nome: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listarAreas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Áreas ativas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaDto"][];
                };
            };
        };
    };
    integridadeHistorico: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resultado da verificação */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegridadeDto"];
                };
            };
            /** @description Sem token, token inválido ou sessão encerrada (NAO_AUTENTICADO) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Não é administrador (ACESSO_NEGADO) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Sessão aberta */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaSessaoDto"];
                };
            };
            /** @description Corpo inválido (DADOS_INVALIDOS) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description E-mail ou senha inválidos (CREDENCIAIS_INVALIDAS) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Mais de 5 tentativas por minuto para o mesmo e-mail (MUITAS_TENTATIVAS) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessão encerrada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sem token, token inválido ou sessão já encerrada (NAO_AUTENTICADO) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    usuarioAtual: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuário atual */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioAtualDto"];
                };
            };
            /** @description Sem token, token inválido ou sessão encerrada (NAO_AUTENTICADO) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    renovarSessao: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            /** @description Novo par de tokens */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaSessaoDto"];
                };
            };
            /** @description Corpo inválido (DADOS_INVALIDOS) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Refresh token desconhecido, expirado, revogado ou reusado (SESSAO_INVALIDA) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Mais de 5 renovações por minuto com o mesmo refresh token (MUITAS_TENTATIVAS) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    gestaoDashboard: {
        parameters: {
            query?: {
                /** @description Janela móvel no fuso America/Sao_Paulo: hoje (desde a meia-noite), 7d, 30d ou tudo (padrão) */
                periodo?: "hoje" | "7d" | "30d" | "tudo";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Painel de gestão */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GestaoDto"];
                };
            };
            /** @description Período inválido (DADOS_INVALIDOS) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Sem token, token inválido ou sessão encerrada (NAO_AUTENTICADO) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Não é administrador (ACESSO_NEGADO) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    resumoDashboard: {
        parameters: {
            query?: {
                /** @description Janela móvel no fuso America/Sao_Paulo: hoje (desde a meia-noite), 7d, 30d ou tudo (padrão) */
                periodo?: "hoje" | "7d" | "30d" | "tudo";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Indicadores */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumoDto"];
                };
            };
            /** @description Período inválido (DADOS_INVALIDOS) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Sem token, token inválido ou sessão encerrada (NAO_AUTENTICADO) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listarSolicitacoes: {
        parameters: {
            query?: {
                /** @description Título, descrição ou código (SOL-000042 ou 42), sem diferenciar maiúsculas e acentos. Depois de tirar os espaços nas pontas: vazio (ignorado) ou de 2 a 200 caracteres */
                q?: string;
                status?: ("ABERTA" | "EM_ANALISE" | "APROVADA" | "REJEITADA") | ("ABERTA" | "EM_ANALISE" | "APROVADA" | "REJEITADA")[];
                prioridade?: ("BAIXA" | "MEDIA" | "ALTA") | ("BAIXA" | "MEDIA" | "ALTA")[];
                /** @description prioridade: ALTA → MEDIA → BAIXA e, dentro, a mais antiga primeiro (ignora direcao). decididoEm: a decisão mais recente primeiro e as sem decisão no fim (ignora direcao) */
                ordenarPor?: "dataSolicitacao" | "prioridade" | "decididoEm";
                direcao?: "asc" | "desc";
                /** @description eu: só as que têm o usuário atual como analista responsável; <id> (UUID): só as desse analista. Ignorado para o solicitante, que vê todas as próprias */
                analista?: "eu" | string;
                /** @description Id da área (UUID); pode repetir: area=<id>&area=<id> */
                area?: string | string[];
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de solicitações */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaSolicitacoesDto"];
                };
            };
            /** @description Parâmetros inválidos (DADOS_INVALIDOS) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Sem token, token inválido ou sessão encerrada (NAO_AUTENTICADO) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    criarSolicitacao: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarSolicitacaoDto"];
            };
        };
        responses: {
            /** @description Criada; o header Location aponta para ela */
            201: {
                headers: {
                    /** @description /api/v1/solicitacoes/{id} */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolicitacaoDto"];
                };
            };
            /** @description Corpo inválido ou com campos não aceitos (DADOS_INVALIDOS) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Sem token, token inválido ou sessão encerrada (NAO_AUTENTICADO) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    detalharSolicitacao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Solicitação */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolicitacaoDto"];
                };
            };
            /** @description Sem token, token inválido ou sessão encerrada (NAO_AUTENTICADO) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Não existe, foi excluída ou não é visível para o usuário (SOLICITACAO_NAO_ENCONTRADA) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    excluirSolicitacao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Excluída */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sem token, token inválido ou sessão encerrada (NAO_AUTENTICADO) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Não é o dono nem administrador (ACESSO_NEGADO) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Não existe, foi excluída ou não é visível para o usuário (SOLICITACAO_NAO_ENCONTRADA) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Status não permite exclusão (EDICAO_BLOQUEADA) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    editarSolicitacao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditarSolicitacaoDto"];
            };
        };
        responses: {
            /** @description Solicitação atualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolicitacaoDto"];
                };
            };
            /** @description Corpo inválido ou com campos não aceitos (DADOS_INVALIDOS) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Sem token, token inválido ou sessão encerrada (NAO_AUTENTICADO) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Não é o dono nem administrador (ACESSO_NEGADO) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Não existe, foi excluída ou não é visível para o usuário (SOLICITACAO_NAO_ENCONTRADA) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Status não permite edição (EDICAO_BLOQUEADA) ou versão desatualizada (CONFLITO_DE_VERSAO) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    iniciarAnalise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Solicitação em análise */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolicitacaoDto"];
                };
            };
            /** @description Sem token, token inválido ou sessão encerrada (NAO_AUTENTICADO) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Cargo sem permissão (ACESSO_NEGADO) ou a própria solicitação (SEGREGACAO_DE_FUNCOES) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Não existe, foi excluída ou não é visível para o usuário (SOLICITACAO_NAO_ENCONTRADA) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description A solicitação não está ABERTA (TRANSICAO_INVALIDA) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    decidirSolicitacao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisaoDto"];
            };
        };
        responses: {
            /** @description Solicitação decidida */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolicitacaoDto"];
                };
            };
            /** @description Corpo inválido ou com campos não aceitos (DADOS_INVALIDOS) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Sem token, token inválido ou sessão encerrada (NAO_AUTENTICADO) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Cargo sem permissão ou não é o responsável (ACESSO_NEGADO), ou a própria solicitação (SEGREGACAO_DE_FUNCOES) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Não existe, foi excluída ou não é visível para o usuário (SOLICITACAO_NAO_ENCONTRADA) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description A solicitação não está EM_ANALISE (TRANSICAO_INVALIDA) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    historicoSolicitacao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Eventos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventoHistoricoDto"][];
                };
            };
            /** @description Sem token, token inválido ou sessão encerrada (NAO_AUTENTICADO) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Não existe, foi excluída ou não é visível para o usuário (SOLICITACAO_NAO_ENCONTRADA) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    reprocessarIntegracao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Solicitação com a integração pendente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolicitacaoDto"];
                };
            };
            /** @description Sem token, token inválido ou sessão encerrada (NAO_AUTENTICADO) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Não é administrador (ACESSO_NEGADO) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Não existe, foi excluída ou não é visível para o usuário (SOLICITACAO_NAO_ENCONTRADA) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description A integração não está em FALHOU (TRANSICAO_INVALIDA) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    reabrirSolicitacao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReaberturaDto"];
            };
        };
        responses: {
            /** @description Solicitação reaberta */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolicitacaoDto"];
                };
            };
            /** @description Corpo inválido ou com campos não aceitos (DADOS_INVALIDOS) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Sem token, token inválido ou sessão encerrada (NAO_AUTENTICADO) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Não é administrador (ACESSO_NEGADO) ou a própria solicitação (SEGREGACAO_DE_FUNCOES) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Não existe, foi excluída ou não é visível para o usuário (SOLICITACAO_NAO_ENCONTRADA) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description A solicitação não está APROVADA nem REJEITADA (TRANSICAO_INVALIDA) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    vivacidade: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Processo de pé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaVivacidadeDto"];
                };
            };
        };
    };
    prontidao: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pronta para atender */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaProntidaoDto"];
                };
            };
            /** @description Algum componente está fora do ar */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaProntidaoDto"];
                };
            };
        };
    };
}
